# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: meamma/example-spring
    docker:
      - image: circleci/openjdk:8-jdk
      - image: docker:17.05.0-ce-git
jobs:
  build:
    executor: docker-publisher

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      - run: gradle build

      - persist_to_workspace:
          root: .
          paths:
            - ./build/libs/demo-0.0.1-SNAPSHOT.jar

      - store_artifacts:
          path: ~/repo/build/libs

  build-docker:
    executor: docker-publisher

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

#      - run:
#          name: Install dependencies
#          command: |
#            apk add --no-cache \
#            py-pip=9.0.0-r1
#            pip install \
#            docker-compose==1.12.0 \
#            awscli==1.11.76

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/app.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t $IMAGE_NAME .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/app.tar $IMAGE_NAME

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/app.tar
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - build-docker:
          requires:
            - build
          filters:
            branches:
              only: master
